posts/urls.py
"""
Module containing urls for the users app.
"""
from django.urls import path
from . import views

# pylint: disable=C0103
app_name = 'posts'

urlpatterns = [
    path('create', views.post_create, name='create'),
    path('feed', views.feed, name='feed'),
    path('like', views.like_post, name='like'),
    path('delete/<int:user_id>/', views.post_delete, name='delete'),
]

snap_vibe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""
Module containing urls for the users app.
"""
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('change_password/',
    auth_view.PasswordChangeView.as_view(template_name='users/change_password.html'),
    name='change_password'),
    path('password_change/done/',
    auth_view.PasswordChangeDoneView.as_view(template_name='users/change_password_done.html'),
    name='password_change_done'),
    path('password_reset/',
    auth_view.PasswordResetView.as_view(template_name='users/password_reset.html'),
    name='password_reset'),
    path('password_reset/done',
    auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    name='password_reset_done'),
    path('reset/<uidb64>/<token>',
    auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
    name='password_reset_confirm'),
    path('password_reset/complete',
    auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
    name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

users/models.py
"""
Module containing models for the users app.
"""
from django.db import models
from django.conf import settings
# Create your models here.
class Profile(models.Model):
    """
    Model representing user profile information.
    """
    user =models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo =models.ImageField(upload_to='users/%Y/%m/%d', blank=True)
    objects = models.Manager()
    def __str__(self):
        """
        Return a string representation of the profile.
        """
        if hasattr(self, 'user') and hasattr(self.user, 'username'):
            return self.user.username
        return 'Profile'
        

users/forms.py
"""
Module containing form definitions for the users app.
"""
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    """
    Form for login the user.
    """
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
class UserRegistrationForm(forms.ModelForm): 
    """
    Form for creating user information.
    """
    password=forms.CharField(label='Password', widget=forms.PasswordInput)
    password2=forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    class Meta:
        """
        Metadata for the UserRegistrationForm.

        Specifies the associated User model and fields for the form.
        """
        model=User
        fields={'username','email','first_name', 'last_name'}
        
    def check_password(self):
        """
        Method to check if the entered passwords match.

        Returns:
            str: The confirmed password.

        Raises:
            forms.ValidationError: If the passwords do not match.
        """
        if self.cleaned_data['password']!=self.cleaned_data['password2']:
            raise forms.ValidationError('Passwords do not match')
        return self.cleaned_data['password2']   
        
class UserEditForm(forms.ModelForm):
    """
    Form for editing user information.
    """
    class Meta:
        """
        Metadata for the UserEditForm.

        Specifies the associated User model and fields for the form.
        """
        model=User
        fields=('first_name','last_name','email')
        
class ProfileEditForm(forms.ModelForm):
    """
    Form for creating/editing user profile information.
    """
    class Meta:
        """
        Metadata for the ProfileEditForm.

        Specifies the associated Profile model and fields for the form.
        """
        model=Profile
        fields=('photo',) 
        

users/views.py
"""
Module containing views for the users app.
"""
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from posts.models import Post
from .models import Profile
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm

# Create your views here.
@csrf_protect
def user_login(request):
    """
    View function for user login.
    """
    if request.method=="POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data= form.cleaned_data
            user= authenticate(request,username=data['username'],password=data['password'])
            if user is not None:
                login(request,user)
                return redirect(reverse('posts:feed'))
            return HttpResponse("Invalid credentials")
    else:            
        form = LoginForm()
    return render(request,'users/login.html',{'form':form})

@login_required  
def index(request):
    """
    View function for index page.
    """
    current_user=request.user
    posts=Post.objects.filter(user=current_user).order_by('-created')
    profile=Profile.objects.filter(user=current_user).first()
    return render(request, 'users/index.html',{'posts':posts, 'profile':profile})

def register(request):
    """
    View function for user registration.
    """
    if request.method=='POST':
        
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user=user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request,'users/register_done.html')
    else:
        user_form=UserRegistrationForm()
        
    return render(request,'users/register.html',{'user_form':user_form})    
    
@login_required
def edit(request):
    """
    View function for editing user info.
    """
    if request.method=='POST':
        user_form=UserEditForm(instance=request.user,data=request.POST)
        profile_form=ProfileEditForm(instance=request.user.profile,
        data=request.POST,files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect(reverse('posts:feed'))
    else:
        user_form=UserEditForm(instance=request.user)
        profile_form=ProfileEditForm(instance=request.user.profile)    
    return render(request,'users/edit.html',{'user_form':user_form,
    'profile_form':profile_form})    
    

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SnapVibe</title>
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <!-- Latest compiled JavaScript -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelector('.footer').classList.add('animated');

            // Add animation to cards while scrolling
            window.addEventListener('scroll', function() {
                const cards = document.querySelectorAll('.card');
                cards.forEach(card => {
                    const cardPosition = card.getBoundingClientRect().top;
                    const screenPosition = window.innerHeight / 1.3; // Adjust the division factor to control when the animation triggers

                    if (cardPosition < screenPosition) {
                        card.classList.add('animate__animated', 'animate__fadeInUp');
                    }
                });
            });
        });
    </script>
     <style>
        body {
            background-image: url("{% static 'users/images/bg15.jpg' %}");
            background-size: cover;
            background-position: center;
        }

        .card {
            background-color: transparent;
            border: none;
        }

        .login-link {
            color: #007bff;
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s;
        }

        .login-link:hover {
            color: #0056b3;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }

            to {
                opacity: 0.7;
            }
        }

        .footer {
            animation: fadeIn 1.5s ease-in-out forwards;
        }
    </style>
    
    <nav class="navbar navbar-light" style="background-color: rgba(255, 255, 255, 0.1);">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'posts:feed' %}">
                <img src="{% static 'users/images/logo.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
                <span>SnapVibe</span>
            </a>
            {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'posts:create' %}">

                <span>Create Post</span>
            </a>
            <a class="navbar-brand" href="{% url 'index' %}">

                <span>My Posts</span>
            </a>
            <a class="navbar-brand" href="{% url 'edit' %}">{{user.username}}</a>

            <a class="navbar-brand" href="{% url 'logout' %}">Logout</a>

            {% else %}
            <a href="{% url 'login' %}">Login</a>
            {% endif %}


        </div>
    </nav>
</head>

<body>
    {% block body %}
    
    {% endblock %}
</body>
<footer class="footer mt-auto py-3 bg-dark text-white">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h5>Connect With Us</h5>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-white">Instagram</a></li>
                    <li><a href="https://www.linkedin.com/in/ayush-jadhav-4749b1148/" class="text-white">LinkedIn</a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <h5>Contact Information</h5>
                <ul class="list-unstyled">
                    <li>Email: jadhavayush2020@gmail.com.com</li>
                    <li>Address: Dublin, Ireland</li>
                </ul>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <p class="text-center">© 2024 SnapVibe. All rights reserved.</p>
            </div>
        </div>
    </div>
</footer>
</html>

users/templates/users/change_password.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
{% endblock %}    

users/templates/users/change_password_done.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
    <h1>Password has been changed successfully!</h1>
{% endblock %}    

users/templates/users/edit.html
{% extends 'users/base.html' %}
{% block body %}
<div class="container mt-5" style="max-width: 600px;">
    <div class="content bg-light p-4 rounded">
        <h2 class="text-center mb-4">Edit Profile form</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <button type="submit" class="btn btn-primary btn-lg btn-block">Update</button>
        </form>
    </div>
</div>
{% endblock %}    

users/templates/users/index.html
{% extends 'users/base.html' %}
{% load static %}

{% block body %}
<div class="container">
<h1>My Posts</h1>
</div>
<div class="container" style="justify-content: center; align-items: center; ">
{% for post in posts%}

<div class="card" style="width: 50rem;">
  <div class="card-header">
    {% if post.user.profile.photo.url is not none %}
    <img src="{{post.user.profile.photo.url}}" alt="" style="border-radius: 50%; height: 50px;  width: 50px;">  
    {% else %}
    <img src="{% static 'users/images/default_profile.png' %}" alt="" style="border-radius: 50%; height: 50px;  width: 50px;">  
    {% endif %}
    {{post.user}}
  </div>    
  <img src="{{post.image.url}}" class="card-img-top" alt="post">
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p class="card-text">{{post.caption}}</p>
    <a href="{% url 'posts:delete' post.id %}">
    <button class="btn btn-danger">Delete</button>
</a>
  </div>
  <div class="card-footer">
    
    {% if logged_user in post.liked_by.all %}
    <a id="{{post.id}}" class="btn-like">
    <img src="{% static 'users/images/like.png' %}" style="border-radius: 50%; height: 50px;  width: 50px;" alt="like">
    </a>
    {% else %}
    <a id="{{post.id}}" class="btn-like">
    <img src="{% static 'users/images/unlike.png' %}" style="border-radius: 50%; height: 50px;  width: 50px;" alt="unlike">
    </a>
    {% endif %}
    
     
  <div>
      {% if post.liked_by.count < 1 %}
      {% elif post.liked_by.count == 1 %}
      {{post.liked_by.first }} Likes this
      {% elif post.liked_by.count > 1 %}
      {{ post.liked_by.first }} & {{post.liked_by.count  }} Likes this
      {% endif %}
  </div>
  <div class="container" style="background-color: white; padding: 10px; margin: 20px; width: 700px">
    {% for comment in post.comment.all %}
    <b>{{ comment.posted_by}}</b>: {{comment.body}}
    {% endfor %} 
  </div>
  <div>
      <div>
        <input type="hidden" name="post_id", id="post_id" value="{{post.id}}">
        <input type="hidden" name="posted_by", id="posted_by" value="{{logged_user}}">
      </div>
  </div>
  </div>
</div>
{% endfor %}
<script type="text/javascript">
    window.CSRF_TOKEN="{{ csrf_token }}"
    $(document).on('click','.btn-like',function(){
        var post_id=this.id
        $.ajax({
            method:"POST",
            url:'/posts/like',
            data:{post_id:post_id, csrfmiddlewaretoken:window.CSRF_TOKEN}
        })
        window.location.href=""
    })
</script>

</div>
{% endblock %}

users/templates/users/login.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
      
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title mb-5" >Login</h2>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-secondary btn-block btn-lg mt-4 mb-5">Login</button>
                        <div class="mb-3">
                            <p><a href="{% url 'password_reset' %}">Forgot Password? Click here to reset password.</a></p>
                        </div>
                        <div class="mb-3">
                            <p><a href="{% url 'register' %}">Dont have an account? Click here to register.</a></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/logout.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
<h1>You have been logged out</h1>
<button type="submit" class="btn btn-secondary btn-block btn-lg mt-4 mb-5" onclick="window.location.href='{% url 'login'%}'">Login</button>
{% endblock %}

users/templates/users/outer_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SnapVibe</title>
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="">
                <img src="{% static 'users/images/logo.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
                <span>SnapVibe</span>
            </a>
        </div>
    </nav>
</head>
<style>
    body {
        background-image: url("{% static 'users/images/bg2.jpg' %}");
        /* Add other background properties as needed */
        background-size: cover; /* Cover the entire viewport */
        
    }
    .card {
        background-color: transparent;
        border: none; /* Remove border if needed */
    }
    .login-link {
        color: #007bff; /* Blue color */
        text-decoration: none; /* Remove underline */
        font-weight: bold; /* Make text bold */
        transition: color 0.3s; /* Add transition effect */
    }

    .login-link:hover {
        color: #0056b3; /* Darker blue color on hover */
    }
</style> 
<body>
    {% block body %}
    {% endblock %}
</body>

</html>

users/templates/users/password_reset.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
    
{% endblock %}    

users/templates/users/password_reset_complete.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
    <h1>Password reset successfully!</h1>
    <a href="{%url 'login'%}">Login</a>
{% endblock %}    

users/templates/users/password_reset_confirm.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
    {% if validlink %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
    {% else %}
    <h2>Password reset link is invalid</h2>
    {% endif %}
{% endblock %}    

users/templates/users/password_reset_done.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
    <h1>Password reset link has been sent to your email successfully!</h1>
    <a href="{%url 'login'%}">Login</a>
{% endblock %}    

users/templates/users/register.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
 
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title mb-5" >User Registration</h2>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{user_form.as_p}}
                        <button type="submit" class="btn btn-success btn-block mt-4 mb-5">Register</button>
                        <div class="mb-3">
                            <p><a href="{% url 'login' %}">Click here to login.</a></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}    

users/templates/users/register_done.html
{% extends 'users/outer_base.html' %}
{% load static %}

{% block body %}
   
    <h2>Registeration successfull</h2>
   <button type="submit" class="btn btn-secondary btn-block btn-lg mt-4 mb-5" onclick="window.location.href='{% url 'login'%}'">Login</button>
{% endblock %}    